# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
# Uncomment options below to use them.
extensions:
  decap_cms:
    branch: main
    collections:
      - name: 'blog'
        label: 'Blog'
        folder: 'content/blog'
        create: true
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Featured", name: "featured", widget: "boolean", default: false}
          - {label: "Draft", name: "draft", widget: "boolean", default: true}
          - {label: "Tags", name: "tags", widget: "list", required: false}
#     publish_mode: editorial_workflow
#     local_backend: true